// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'core/scene.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 519880953;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_rust_3d',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiSimpleAddCube({
    required Scene3D scene,
    required double x,
    required double y,
    required double z,
    required double r,
    required double g,
    required double b,
  });

  Future<Scene3D> crateApiSimpleCreateScene();

  Future<double> crateApiSimpleGetCameraFov({required Scene3D scene});

  Future<(double, double, double)> crateApiSimpleGetCameraPosition({
    required Scene3D scene,
  });

  Future<(double, double, double)> crateApiSimpleGetCameraTarget({
    required Scene3D scene,
  });

  Future<void> crateApiSimpleInitApp();

  void crateApiSimpleInitDefaultCamera({required Scene3D scene});

  Future<PlatformInt64> crateApiSimpleInitNativeTexture({
    required Scene3D scene,
    required PlatformInt64 engineHandle,
    required int width,
    required int height,
  });

  void crateApiSimpleJumpPlayer({required Scene3D scene});

  void crateApiSimpleMovePlayer({
    required Scene3D scene,
    required double dx,
    required double dz,
  });

  void crateApiSimpleOrbitCamera({
    required Scene3D scene,
    required double dx,
    required double dy,
  });

  void crateApiSimplePhysicsStep({required Scene3D scene, required double dt});

  Future<void> crateApiSimpleRenderNativeFrame({
    required Scene3D scene,
    required int width,
    required int height,
  });

  Future<Uint8List> crateApiSimpleRenderScene({
    required Scene3D scene,
    required int width,
    required int height,
  });

  Future<void> crateApiSimpleSetCameraFov({
    required Scene3D scene,
    required double fov,
  });

  BigInt crateApiSimpleSpawnCubeInFront({
    required Scene3D scene,
    required double r,
    required double g,
    required double b,
  });

  void crateApiSimpleUpdateNodeTransform({
    required Scene3D scene,
    required BigInt nodeId,
    required double px,
    required double py,
    required double pz,
    required double rx,
    required double ry,
    required double rz,
    required double sx,
    required double sy,
    required double sz,
  });

  void crateApiSimpleZoomCamera({
    required Scene3D scene,
    required double delta,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Scene3D;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Scene3D;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Scene3DPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiSimpleAddCube({
    required Scene3D scene,
    required double x,
    required double y,
    required double z,
    required double r,
    required double g,
    required double b,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_f_32(z, serializer);
          sse_encode_f_32(r, serializer);
          sse_encode_f_32(g, serializer);
          sse_encode_f_32(b, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAddCubeConstMeta,
        argValues: [scene, x, y, z, r, g, b],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAddCubeConstMeta => const TaskConstMeta(
    debugName: "add_cube",
    argNames: ["scene", "x", "y", "z", "r", "g", "b"],
  );

  @override
  Future<Scene3D> crateApiSimpleCreateScene() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCreateSceneConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateSceneConstMeta =>
      const TaskConstMeta(debugName: "create_scene", argNames: []);

  @override
  Future<double> crateApiSimpleGetCameraFov({required Scene3D scene}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetCameraFovConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCameraFovConstMeta =>
      const TaskConstMeta(debugName: "get_camera_fov", argNames: ["scene"]);

  @override
  Future<(double, double, double)> crateApiSimpleGetCameraPosition({
    required Scene3D scene,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_f_32_f_32_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetCameraPositionConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCameraPositionConstMeta =>
      const TaskConstMeta(
        debugName: "get_camera_position",
        argNames: ["scene"],
      );

  @override
  Future<(double, double, double)> crateApiSimpleGetCameraTarget({
    required Scene3D scene,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_f_32_f_32_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetCameraTargetConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCameraTargetConstMeta =>
      const TaskConstMeta(debugName: "get_camera_target", argNames: ["scene"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiSimpleInitDefaultCamera({required Scene3D scene}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitDefaultCameraConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitDefaultCameraConstMeta =>
      const TaskConstMeta(
        debugName: "init_default_camera",
        argNames: ["scene"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleInitNativeTexture({
    required Scene3D scene,
    required PlatformInt64 engineHandle,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_i_64(engineHandle, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitNativeTextureConstMeta,
        argValues: [scene, engineHandle, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitNativeTextureConstMeta =>
      const TaskConstMeta(
        debugName: "init_native_texture",
        argNames: ["scene", "engineHandle", "width", "height"],
      );

  @override
  void crateApiSimpleJumpPlayer({required Scene3D scene}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleJumpPlayerConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJumpPlayerConstMeta =>
      const TaskConstMeta(debugName: "jump_player", argNames: ["scene"]);

  @override
  void crateApiSimpleMovePlayer({
    required Scene3D scene,
    required double dx,
    required double dz,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(dx, serializer);
          sse_encode_f_32(dz, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMovePlayerConstMeta,
        argValues: [scene, dx, dz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMovePlayerConstMeta => const TaskConstMeta(
    debugName: "move_player",
    argNames: ["scene", "dx", "dz"],
  );

  @override
  void crateApiSimpleOrbitCamera({
    required Scene3D scene,
    required double dx,
    required double dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(dx, serializer);
          sse_encode_f_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleOrbitCameraConstMeta,
        argValues: [scene, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOrbitCameraConstMeta => const TaskConstMeta(
    debugName: "orbit_camera",
    argNames: ["scene", "dx", "dy"],
  );

  @override
  void crateApiSimplePhysicsStep({required Scene3D scene, required double dt}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(dt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePhysicsStepConstMeta,
        argValues: [scene, dt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePhysicsStepConstMeta =>
      const TaskConstMeta(debugName: "physics_step", argNames: ["scene", "dt"]);

  @override
  Future<void> crateApiSimpleRenderNativeFrame({
    required Scene3D scene,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRenderNativeFrameConstMeta,
        argValues: [scene, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRenderNativeFrameConstMeta =>
      const TaskConstMeta(
        debugName: "render_native_frame",
        argNames: ["scene", "width", "height"],
      );

  @override
  Future<Uint8List> crateApiSimpleRenderScene({
    required Scene3D scene,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRenderSceneConstMeta,
        argValues: [scene, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRenderSceneConstMeta => const TaskConstMeta(
    debugName: "render_scene",
    argNames: ["scene", "width", "height"],
  );

  @override
  Future<void> crateApiSimpleSetCameraFov({
    required Scene3D scene,
    required double fov,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(fov, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSetCameraFovConstMeta,
        argValues: [scene, fov],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetCameraFovConstMeta => const TaskConstMeta(
    debugName: "set_camera_fov",
    argNames: ["scene", "fov"],
  );

  @override
  BigInt crateApiSimpleSpawnCubeInFront({
    required Scene3D scene,
    required double r,
    required double g,
    required double b,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(r, serializer);
          sse_encode_f_32(g, serializer);
          sse_encode_f_32(b, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSpawnCubeInFrontConstMeta,
        argValues: [scene, r, g, b],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSpawnCubeInFrontConstMeta =>
      const TaskConstMeta(
        debugName: "spawn_cube_in_front",
        argNames: ["scene"],
      );

  @override
  void crateApiSimpleUpdateNodeTransform({
    required Scene3D scene,
    required BigInt nodeId,
    required double px,
    required double py,
    required double pz,
    required double rx,
    required double ry,
    required double rz,
    required double sx,
    required double sy,
    required double sz,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_u_64(nodeId, serializer);
          sse_encode_f_32(px, serializer);
          sse_encode_f_32(py, serializer);
          sse_encode_f_32(pz, serializer);
          sse_encode_f_32(rx, serializer);
          sse_encode_f_32(ry, serializer);
          sse_encode_f_32(rz, serializer);
          sse_encode_f_32(sx, serializer);
          sse_encode_f_32(sy, serializer);
          sse_encode_f_32(sz, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleUpdateNodeTransformConstMeta,
        argValues: [scene, nodeId, px, py, pz, rx, ry, rz, sx, sy, sz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateNodeTransformConstMeta =>
      const TaskConstMeta(
        debugName: "update_node_transform",
        argNames: [
          "scene",
          "nodeId",
          "px",
          "py",
          "pz",
          "rx",
          "ry",
          "rz",
          "sx",
          "sy",
          "sz",
        ],
      );

  @override
  void crateApiSimpleZoomCamera({
    required Scene3D scene,
    required double delta,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
            scene,
            serializer,
          );
          sse_encode_f_32(delta, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleZoomCameraConstMeta,
        argValues: [scene, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleZoomCameraConstMeta => const TaskConstMeta(
    debugName: "zoom_camera",
    argNames: ["scene", "delta"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Scene3D => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Scene3D => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D;

  @protected
  Scene3D
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Scene3DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Scene3D
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Scene3DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Scene3D
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Scene3DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Scene3D
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Scene3DImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  (double, double, double) dco_decode_record_f_32_f_32_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_f_32(arr[0]),
      dco_decode_f_32(arr[1]),
      dco_decode_f_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Scene3D
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Scene3DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Scene3D
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Scene3DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Scene3D
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Scene3DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Scene3D
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Scene3DImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  (double, double, double) sse_decode_record_f_32_f_32_f_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_32(deserializer);
    var var_field1 = sse_decode_f_32(deserializer);
    var var_field2 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    Scene3D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Scene3DImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    Scene3D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Scene3DImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    Scene3D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Scene3DImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScene3D(
    Scene3D self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Scene3DImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_record_f_32_f_32_f_32(
    (double, double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.$1, serializer);
    sse_encode_f_32(self.$2, serializer);
    sse_encode_f_32(self.$3, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class Scene3DImpl extends RustOpaque implements Scene3D {
  // Not to be used by end users
  Scene3DImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Scene3DImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Scene3D,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Scene3D,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Scene3DPtr,
  );
}
