// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/scene.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Scene3D> createScene() =>
    RustLib.instance.api.crateApiSimpleCreateScene();

Future<BigInt> addCube({
  required Scene3D scene,
  required double x,
  required double y,
  required double z,
  required double r,
  required double g,
  required double b,
}) => RustLib.instance.api.crateApiSimpleAddCube(
  scene: scene,
  x: x,
  y: y,
  z: z,
  r: r,
  g: g,
  b: b,
);

void physicsStep({required Scene3D scene, required double dt}) =>
    RustLib.instance.api.crateApiSimplePhysicsStep(scene: scene, dt: dt);

void initDefaultCamera({required Scene3D scene}) =>
    RustLib.instance.api.crateApiSimpleInitDefaultCamera(scene: scene);

void orbitCamera({
  required Scene3D scene,
  required double dx,
  required double dy,
}) => RustLib.instance.api.crateApiSimpleOrbitCamera(
  scene: scene,
  dx: dx,
  dy: dy,
);

void zoomCamera({required Scene3D scene, required double delta}) =>
    RustLib.instance.api.crateApiSimpleZoomCamera(scene: scene, delta: delta);

bool handlePointerDown({
  required Scene3D scene,
  required double screenX,
  required double screenY,
  required double screenWidth,
  required double screenHeight,
}) => RustLib.instance.api.crateApiSimpleHandlePointerDown(
  scene: scene,
  screenX: screenX,
  screenY: screenY,
  screenWidth: screenWidth,
  screenHeight: screenHeight,
);

void handlePointerMove({
  required Scene3D scene,
  required double screenX,
  required double screenY,
  required double screenWidth,
  required double screenHeight,
}) => RustLib.instance.api.crateApiSimpleHandlePointerMove(
  scene: scene,
  screenX: screenX,
  screenY: screenY,
  screenWidth: screenWidth,
  screenHeight: screenHeight,
);

void handlePointerUp({required Scene3D scene}) =>
    RustLib.instance.api.crateApiSimpleHandlePointerUp(scene: scene);

Future<Uint8List> renderScene({
  required Scene3D scene,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleRenderScene(
  scene: scene,
  width: width,
  height: height,
);

void updateCamera({
  required Scene3D scene,
  required double px,
  required double py,
  required double pz,
  required double tx,
  required double ty,
  required double tz,
}) => RustLib.instance.api.crateApiSimpleUpdateCamera(
  scene: scene,
  px: px,
  py: py,
  pz: pz,
  tx: tx,
  ty: ty,
  tz: tz,
);

void updateNodeTransform({
  required Scene3D scene,
  required BigInt nodeId,
  required double px,
  required double py,
  required double pz,
  required double rx,
  required double ry,
  required double rz,
  required double sx,
  required double sy,
  required double sz,
}) => RustLib.instance.api.crateApiSimpleUpdateNodeTransform(
  scene: scene,
  nodeId: nodeId,
  px: px,
  py: py,
  pz: pz,
  rx: rx,
  ry: ry,
  rz: rz,
  sx: sx,
  sy: sy,
  sz: sz,
);

Future<(double, double, double)> getCameraPosition({required Scene3D scene}) =>
    RustLib.instance.api.crateApiSimpleGetCameraPosition(scene: scene);

Future<(double, double, double)> getCameraTarget({required Scene3D scene}) =>
    RustLib.instance.api.crateApiSimpleGetCameraTarget(scene: scene);

Future<double> getCameraFov({required Scene3D scene}) =>
    RustLib.instance.api.crateApiSimpleGetCameraFov(scene: scene);

Future<void> setCameraPosition({
  required Scene3D scene,
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleSetCameraPosition(
  scene: scene,
  x: x,
  y: y,
  z: z,
);

Future<void> setCameraTarget({
  required Scene3D scene,
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleSetCameraTarget(
  scene: scene,
  x: x,
  y: y,
  z: z,
);

Future<void> setCameraFov({required Scene3D scene, required double fov}) =>
    RustLib.instance.api.crateApiSimpleSetCameraFov(scene: scene, fov: fov);

Future<PlatformInt64> initNativeTexture({
  required Scene3D scene,
  required PlatformInt64 engineHandle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleInitNativeTexture(
  scene: scene,
  engineHandle: engineHandle,
  width: width,
  height: height,
);

Future<void> renderNativeFrame({
  required Scene3D scene,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleRenderNativeFrame(
  scene: scene,
  width: width,
  height: height,
);
